name: Label New Issues

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add enhancement label if no labels are present
        uses: actions/github-script@v7
        with:
          script: |
            const issueLabels = context.payload.issue.labels;
            if (issueLabels.length === 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ['enhancement']
              });
            }

  issue_branch:
    runs-on: ubuntu-latest
    needs: add_label
    outputs:
      branch_name: ${{ steps.issue_branch1.outputs.branch_name }}
    steps:
      - name: Create branch from issue
        uses: actions/github-script@v7
        id: issue_branch1
        with:
          script: |

            const issueTitle = context.payload.issue.title;
            const issueNumber = context.payload.issue.number;
            const issueLabels = context.payload.issue.labels.map(label => label.name);
            let branchName;
            if (issueLabels.includes('enhancement')) {
              branchName = `feature/#${issueNumber}`;
              core.setOutput("branch_name", branchName);
            } else if (issueLabels.includes('bug')) {
              branchName = `bugfix/#${issueNumber}`;
              core.setOutput("branch_name", branchName);
            } else {
              return;
            }

  git_operations:
    runs-on: ubuntu-latest
    needs: issue_branch
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        with:
          branch: ${{ needs.issue_branch.outputs.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
