name: Label New Issues

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    environment: CI_CD
    steps:
      - name: Add enhancement label if no labels are present
        if: ${{ github.event.issue.labels.length == 0 }}
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: enhancement
        run: gh issue edit "$NUMBER" --add-label "$LABELS"

        # uses: actions/github-script@v7
        # with:
        #   script: |
        #     const issueLabelNames = context.payload.issue.labels.map(label => label.name);
        #     if (issueLabelNames.length === 0) {
        #       await github.rest.issues.addLabels({
        #         owner: context.repo.owner,
        #         repo: context.repo.repo,
        #         issue_number: context.payload.issue.number,
        #         labels: ['enhancement']
        #       });
        #     }
